"""Second Migration

Revision ID: 435f2223d070
Revises: cb6379e8e71c
Create Date: 2022-05-10 11:28:34.632502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435f2223d070'
down_revision = 'cb6379e8e71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
